version: '3.9'

volumes:
  data:

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - path: .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      PGDATA: /data/postgres
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - data:/data/postgres
