version: '3.9'

volumes:
  data:

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file: &env_file
      - path: .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      PGDATA: /data/postgres
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - data:/data/postgres
  yatodo:
    build:
      dockerfile: Dockerfile
      args:
        DESTINATION: dev
    ports:
      - 8081:8081
    env_file: *env_file
    environment:
      DB_HOSTNAME: host.docker.internal
    
