apiVersion: v1
kind: Service
metadata:
  name: yatodo
spec:
  selector:
    app: yatodo
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8081
      protocol: TCP
      name: https
  type: LoadBalancer
