kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: yatodo
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
      - containerPort: 30001
        hostPort: 443
  - role: worker
    # extraMounts:
    # - hostPath: /path/to/my/files
    #   containerPath: /files
  - role: worker
  - role: worker
