apiVersion: v1
kind: Service
metadata:
  name: yatodo-db
spec:
  selector:
    app: yatodo-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  type: ClusterIP
